;este programa enciende o apaga un ledcada vez que se presiona un boton conectado a RE0
;este está conectado a un resistor pull down
    
    
    LIST P=18F4550
    #INCLUDE <P18F4550.INC>
    
#DEFINE	CERO	B'00111111'
#DEFINE	UNO	B'00000110'
#DEFINE	DOS	B'01011011'
#DEFINE	TRES	B'01001111'
#DEFINE	CUATRO	B'01100110'
#DEFINE	CINCO	B'01101101'
#DEFINE	SEIS	B'01111100'
#DEFINE	SIETE	B'00000111'
#DEFINE	OCHO	B'01111111'
#DEFINE	NUEVE	B'01100111'
    
CBLOCK .3
    DATOA
    DATOB
ENDC
    
    ORG .0
    
  GOTO SETTINGS
  
TABLA
    ADDWF   PCL,F,0 ;PCL=DATOA+W    34
    DT CERO,UNO,DOS,TRES,CUATRO,CINCO,SEIS,SIETE,OCHO,NUEVE
    
SETTINGS
    SETF    TRISE,0
    CLRF    TRISD,0
    MOVLW   .15
    MOVWF   ADCON1,0
    CLRF    PORTD,0
    CLRF    PORTE,0
    MOVLW   B'11010111'
    MOVWF   T0CON,0
    MOVLW   B'00111111'
    MOVWF   PORTD,0
    MOVLW   .0
    MOVWF   DATOA,0
    
MAIN
    BTFSS  PORTE,RE0,0   ;SE PREGUNTA SI EL BOTÓN1 ESTÁ en 1
    GOTO   SUBE    
    BTFSS  PORTE,RE1,0   ;SE PREGUNTA SI EL BOTÓN2 ESTÁ en 1
    GOTO   BAJA
    GOTO MAIN
    
SUBE
    CALL RETARDO
    BTFSS  PORTE,RE0,0
    GOTO SUBE
    MOVLW .9
    CPFSLT DATOA,0
    GOTO MAIN
    MOVLW .1
    ADDWF DATOA,1,0
    MOVF DATOA,0,0
    MULLW .2	
    MOVF  PRODL,W,0
    CALL TABLA
    MOVWF PORTD,0
    GOTO MAIN
    
BAJA
    CALL RETARDO
    BTFSS  PORTE,RE1,0
    GOTO BAJA
    MOVLW .0
    CPFSGT DATOA,0
    GOTO MAIN
    MOVFF DATOA,DATOB
    MOVLW .1
    SUBWF DATOA,W,0
    MOVWF DATOA,0
    MULLW .2	
    MOVF  PRODL,W,0
    CALL TABLA
    MOVWF PORTD,0
    GOTO MAIN
    
    
RETARDO
    CLRF    TMR0L,0 ;CUENTA DE 0 A 255, PORQUE ES A 8 BITS
    MOVLW   .15
    
ASK
    CPFSEQ  TMR0L,0 ;PREGUNTA SI W=15, VALE LO MISMO QUE TMR0L
    BRA	    ASK
    RETURN
    END








