;este programa enciende o apaga un ledcada vez que se presiona un boton conectado a RE0
;este está conectado a un resistor pull down
    
    
    LIST P=18F4550
    #INCLUDE <P18F4550.INC>
    
    #DEFINE BOTON   PORTE,RE0,0
    #DEFINE LED	    PORTD,RD1,0
    
    ORG .0
    
SETTINGS
    BSF	    TRISE,0,0
    BCF	    TRISD,1,0
    MOVLW   .15
    MOVWF   ADCON1,0
    CLRF    PORTD,0
    CLRF    PORTE,0
    MOVLW   B'11010111'
    MOVWF   T0CON,0
    
MAIN
    BTFSS  BOTON   ;SE PREGUNTA SI EL BOTÓN ESTÁ en 1
    BRA    MAIN    ;BRA ES COMO GOTO, PERO PARA SALTOS BEBÉ
    
DELAY
    CALL   RETARDO  ;ESPERAR 20mS PARA QUE TERMINE EL REBOTE
    BTFSC  BOTON    ;SE PREGUNTA SI YA SOLTARON EL BOTÓN
    BRA	   DELAY    ;VUELVE A PREGUNTAR HASTA QUE LO SUELTEN
    
ACCIONESPERADA
    BTG	    LED	    ;ENCIENDE O APAGA EL LED SEGUN SEA EL CASO
    BRA	    MAIN    ;VUELVE A PREGUNTAR POR EL BOTÓN
    
RETARDO
    CLRF    TMR0L,0 ;CUENTA DE 0 A 255, PORQUE ES A 8 BITS
    MOVLW   .15
    
ASK
    CPFSEQ  TMR0L,0 ;PREGUNTA SI W=15, VALE LO MISMO QUE TMR0L
    BRA	    ASK
    RETURN
    END


