;ESTE PROGRAMA, PERMITE MOSTRAR EN LOS PUERTOS B Y D EL VALOR BINARIO
;CORRESPONDIENTE A LA SEÑAL ANALOGICA INTRODUCIDA EN EL AN0 (CANAL 0)
;EL Vref ES EL MISMO QUE ALIMENTA EL PIC (VCFG1, VCFG0 TIENEN VALOR 00)
;EL FORMATO DE CONVERTIDOR ES HACIA LA IZQUIERDA
;LA SEÑAL ANALOGICA SERA PROPORCIONADA POR UN POTENCIOMETRO
    
    LIST P=18F4550
    #INCLUDE<P18F4550.INC>
    
    ORG .0
    
INICIO
    BSF	    TRISA,0,0	;AN0 ES ENTRADA
    CLRF    PORTA,0	;LIMPIAR PA
    CLRF    TRISD,0	;PD ES SALIDA
    CLRF    TRISB,0	;PB ES SALIDA
    CLRF    PORTB,0	;LIMPIAR PB
    CLRF    PORTD,0	;LIMPIAR PD
    MOVLW   .7
    MOVWF   CMCON	;COMPARADOR DE VOLTAJES OFF
    MOVLW   B'00000001'
    MOVWF   ADCON0,0	;CAD ACTIVADO, CANAL 0 SELECCIONADO
    MOVLW   B'00001110'	
    MOVWF   ADCON1,0	;AN0 ES ANALOGICO Y Vref ES EL MISMO DEL PIC
    MOVLW   B'00100111'
    MOVWF   ADCON2	;FORMATO IZQ MODO DUMMIES
    
MAIN
    BSF	    ADCON0,GO_DONE,0	;EL BIT 1 SE LLAMA GODON :P, ESTATUS DE CONVERSIÓN, PUES INICIA CONVERSIÓN
ASK
    BTFSC   ADCON0,GO_DONE,	;¿YA TERMINÓ LA CONVERSIÓN, GODON?
    BRA	    ASK			
    MOVFF   ADRESH,PORTB	;VALORES DE CONVERSIÓN A PUERTO
    MOVFF   ADRESL,PORTD	;VALORES DE CONVERSIÓN A PUERTO
    GOTO    MAIN
    END