;ESTE PROGRAMA, PERMITE MOSTRAR EN LOS PUERTOS B Y D EL VALOR BINARIO
;CORRESPONDIENTE A LA SEÑAL ANALOGICA INTRODUCIDA EN EL AN0 (CANAL 0)
;EL Vref ES EL MISMO QUE ALIMENTA EL PIC (VCFG1, VCFG0 TIENEN VALOR 00)
;EL FORMATO DE CONVERTIDOR ES HACIA LA IZQUIERDA
;LA SEÑAL ANALOGICA SERA PROPORCIONADA POR UN POTENCIOMETRO
    
    LIST P=18F4550
    #INCLUDE<P18F4550.INC>
    
    CBLOCK .5
	DATOA
	DATOB
    ENDC	
    ORG .0
    
INICIO
    BSF	    TRISA,0,0	;AN0 ES ENTRADA
    CLRF    PORTA,0	;LIMPIAR PA
    CLRF    TRISD,0	;PD ES SALIDA
    CLRF    TRISB,0	;PB ES SALIDA
    CLRF    PORTB,0	;LIMPIAR PB
    CLRF    PORTD,0	;LIMPIAR PD
    MOVLW   .7
    MOVWF   CMCON	;COMPARADOR DE VOLTAJES OFF
    MOVLW   B'00000001'
    MOVWF   ADCON0,0	;CAD ACTIVADO, CANAL 0 SELECCIONADO
    MOVLW   B'00001110'	
    MOVWF   ADCON1,0	;AN0 ES ANALOGICO Y Vref ES EL MISMO DEL PIC
    MOVLW   B'00100111'
    MOVWF   ADCON2	;FORMATO IZQ MODO DUMMIES
    
MAIN
    BSF	    ADCON0,GO_DONE,0	;ESTATUS DE CONVERSIÓN, INICIA CONVERSIÓN
ASK
    BTFSC   ADCON0,GO_DONE,	;¿YA TERMINÓ LA CONVERSIÓN?
    BRA	    ASK			
    MOVFF  ADRESH,DATOA	;VALORES DE CONVERSIÓN A UN REGISTRO
    MOVFF  ADRESL,DATOB	;VALORES DE CONVERSIÓN A UN REGISTRO (AHORA MISMO NO HACE NADA)
    GOTO   LED
    
LED
    MOVLW B'10111100'
    CPFSGT DATOA,1
    GOTO  APAGA
    BSF   PORTB,RB0,0
    GOTO MAIN
    
APAGA
    BCF PORTB,RB0,0
    GOTO MAIN
    END


