  
    LIST P=18F4550
    #INCLUDE<P18F4550.INC>
    
;CONFIG1L dir 300000h 	20
		;CONFIG	PLLDIV=1	 ; 
		;CONFIG	CPUDIV=OSC1_PLL2 ;CUANDO SE USA XTAL	
		;CONFIG	USBDIV=2

		;CONFIG1H dir 300001h	08
		CONFIG	FOSC=INTOSCIO_EC ;OSCILADOR INTERNO, RA6 COMO PIN, USB USA OSC EC
		CONFIG	FCMEN=OFF        ;DESHABILITDO EL MONITOREO DEL RELOJ
		CONFIG	IESO=OFF

		;CONFIG2L DIR 300002H	38
		CONFIG	PWRT=ON          ;PWRT HABILITADO
		CONFIG  BOR=OFF		 ;BROWN OUT RESET DESHABILITADO
		CONFIG BORV=3		 ;RESET AL MINIMO VOLTAJE NO UTILZADO EN ESTE CASO
		CONFIG	VREGEN=ON	 ;REULADOR DE USB ENCENDIDO

		;CONFIG2H DIR 300003H	1E
		CONFIG	WDT=OFF          ;WACH DOG DESHABILITADO
		CONFIG WDTPS=32768      ;TIMER DEL WATCHDOG 
		
		;CONFIG3H DIR 300005H	81
		CONFIG	CCP2MX=ON	 ;CCP2 MULTIPLEXADAS CON RC1	
		CONFIG	PBADEN=OFF       ;PUERTO B PINES DEL 0 AL 4 ENTRADAS DIGITALES
		CONFIG  LPT1OSC=OFF	 ;TIMER1 CONFIURADO PARA OPERAR EN BAJA POTENCIA
		CONFIG	MCLRE=ON         ;MASTER CLEAR HABILITADO
		
		;CONFIG4L DIR 300006H	81
		CONFIG	STVREN=ON	 ;SI EL STACK SE LLENA CAUSE RESET		
		CONFIG	LVP=OFF		 ;PROGRAMACIÒN EN BAJO VOLTAJE APAGADO
		CONFIG	ICPRT=OFF	 ;REGISTRO ICPORT DESHABILITADO
		CONFIG	XINST=OFF	 ;SET DE EXTENCION DE INSTRUCCIONES Y DIRECCIONAMIENTO INDEXADO DESHABILITADO

		;CONFIG5L DIR 300008H	0F
		CONFIG	CP0=OFF		 ;LOS BLOQUES DEL CÒDIGO DE PROGRAMA
		CONFIG	CP1=OFF          ;NO ESTAN PROTEGIDOS
		CONFIG	CP2=OFF		 
		CONFIG	CP3=OFF
		
		;CONFIG5H DR 300009H	C0
		CONFIG	CPB=OFF		 ;SECTOR BOOT NO ESTA PROTEGIDO
		CONFIG	CPD=OFF		 ;EEPROM N PROTEGIDA

		;CONFIG6L DIR 30000AH	0F
		CONFIG	 WRT0=OFF	 ;BLOQUES NO PROTEGIDOS CONTRA ESCRITURA
		CONFIG	 WRT1=OFF
		CONFIG	 WRT2=OFF
		CONFIG	 WRT3=OFF

		;CONFIG6H DIR 30000BH	E0
		CONFIG	 WRTC=OFF	 ;CONFIGURACION DE REGISTROS NO PROTEGIDO
		CONFIG	 WRTB=OFF	 ;BLOQUE BOOTEBLE NO PROTEGIDO
		CONFIG	 WRTD=OFF	 ;EEPROMDE DATOS NO PROTGIDA

		;CONFIG7L DIR 30000CH	0F
		CONFIG	 EBTR0=OFF	 ;TABLAS DE LETURA NO PROTEGIDAS
		CONFIG	 EBTR1=OFF
		CONFIG	 EBTR2=OFF
		CONFIG	 EBTR3=OFF

		;CONFIG7H DIR 30000DH	40
		CONFIG	 EBTRB=OFF	 ;TABLAS NO PROTEGIDAS
    
#DEFINE	CERO	B'0111111'
#DEFINE	UNO	B'0001010'
#DEFINE	DOS	B'1011101'
#DEFINE	TRES	B'1011011'
#DEFINE	CUATRO	B'1101010'
#DEFINE	CINCO	B'1110011'
#DEFINE	SEIS	B'1110111'
#DEFINE	SIETE	B'0011010'
#DEFINE	OCHO	B'1111111'
#DEFINE	NUEVE	B'1111010'
#DEFINE	DIEZ	B'1111110'
#DEFINE	ONCE	B'1100111'
#DEFINE	DOCE	B'0110101'
#DEFINE	TRECE	B'1001111'
#DEFINE	CATORCE	B'1110101'
#DEFINE	QUINCE	B'1110100'
		
cblock .10
	DATOA
	DATOB
	DATOC
	MENOS
	RESTAR
ENDC
#define SWITCH1 PORTB,RB0,0
#define SWITCH2 PORTB, RB1,0
ORG	.0
	
  GOTO CONFIGURACION
  
TABLA
    ADDWF   PCL,F,0 ;PCL=DATOA+W    34
    DT CERO,UNO,DOS,TRES,CUATRO,CINCO,SEIS,SIETE,OCHO,NUEVE,DIEZ,ONCE,DOCE,TRECE,CATORCE,QUINCE
    
CONFIGURACION
    CLRF    PORTA,0   ;10
    CLRF    PORTD,0   ;12
    CLRF    PORTB,0
    SETF    TRISA,0 ;PC=0
    SETF    TRISB,0
    MOVLW   .15	;PC=2
    MOVWF   ADCON1,0  ;4
    MOVLW   .7	;6
    MOVWF   CMCON,0   ;8  
    CLRF    TRISD,0   ;14
   
 OPERANDO
    MOVLW B'00000000'
    MOVWF MENOS,1
    MOVFF PORTA,DATOA
    MOVLW B'00000111'
    ANDWF DATOA,F,1
    MOVFF PORTA,DATOB
    MOVLW B'00111000'
    ANDWF DATOB,F,1
    RRNCF DATOB,F,1
    RRNCF DATOB,F,1
    RRNCF DATOB,W,1
    BTFSC SWITCH1    
    BTFSS SWITCH1 
    GOTO SUMA
    BTFSS SWITCH2 
    GOTO RESTA
    GOTO MUL

SUMA
    ADDWF DATOA,W,1
    MULLW   .2	;24
    MOVF    PRODL,W,0	;26
    CALL TABLA
    MOVWF PORTD,0
    GOTO OPERANDO
 
 RESTA
    SUBWF DATOA,W,1
    MOVWF RESTAR,1
    MOVLW B'00000000'
    BTFSC STATUS,N,0
    MOVLW B'10000000'
    BTFSC STATUS,N,0
    NEGF  RESTAR,0
    MOVWF MENOS,1
    MOVFF RESTAR,WREG
    MULLW   .2	
    MOVF    PRODL,W,0
    CALL TABLA
    ADDWF MENOS,W,1
    MOVWF PORTD,0
    GOTO OPERANDO
 
 MUL
    MULWF DATOA,W
    MOVF PRODL,W,0
    MULLW   .2	;24
    MOVF    PRODL,W,0	;26
    CALL TABLA
    MOVWF PORTD,0
 GOTO OPERANDO

END


