LIST P = 18F4550

#INCLUDE <P18F4550.INC>

ORG .0
    
SETTINGS    
    CLRF PORTC ;LIMPIAMOS PUERTO C
    CLRF PORTB ;LIMPIAMOS PUERTO B
    CLRF PORTD ;LIMPIAMOS PUERTO D
    CLRF PORTA ;LIMPIAMOS PUERTO A
    CLRF TRISC ;PUERTO C ES ENTRAA
    SETF TRISB ;PUERTO B ES ENTRADA
    CLRF TRISA ;PUERTO A ES SALIDA
    CLRF TRISD ;PUERTO D ES SALIDA
    CLRF PORTE ;LIMPIAMOS PUERTO A
    SETF TRISE ;PUERTO C ES ENTRAA
    MOVLW   .7
    MOVWF   CMCON	;COMPARADOR DE VOLTAJES OFF
    MOVLW   .15
    MOVWF   ADCON1	
    MOVLW B'11010111'
    MOVWF T0CON


MAIN
    BTFSS PORTB,RB0,0
    GOTO noHayAgua
    BCF PORTC,RC0,0
    BTFSC PORTB,RB1,0
    GOTO CHECAR
    BTFSS PORTB,RB2,0  ;SENSOR B
    GOTO dosBOMBAS
    GOTO unaBOMBA
    GOTO MAIN
    
noHayAgua
    BSF PORTC,RC0,0
    GOTO MAIN

CHECAR    
    BTFSS PORTB,RB2,0  ;SENSOR B
    GOTO PROBLEMA
    GOTO MAIN
    
PROBLEMA
    BSF PORTC,RC1,0
    CALL DELAY
    CALL DELAY
    CALL DELAY
    BCF PORTC,RC1,0
    CALL DELAY
    CALL DELAY
    CALL DELAY
    BSF PORTC,RC1,0
    CALL DELAY
    CALL DELAY
    CALL DELAY
    BCF PORTC,RC1,0
    GOTO MAIN

dosBOMBAS
    MOVLW B'11001100'
    MOVWF PORTD,0
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    BTFSC PORTB,RB2,0  ;SENSOR B
    GOTO MAIN
    BTFSC PORTE,RE0,0  ;TEMP B1
    GOTO BOMBAB2
    BTFSC PORTE,RE1,0  ;TEMP B2
    GOTO BOMBAB1
    MOVLW B'01100110'
    MOVWF PORTD,0
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    BTFSC PORTB,RB2,0  ;SENSOR B
    GOTO MAIN
    BTFSC PORTE,RE0,0  ;TEMP B1
    GOTO BOMBAB2
    BTFSC PORTE,RE1,0  ;TEMP B2
    GOTO BOMBAB1
    MOVLW B'00110011'
    MOVWF PORTD,0
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    BTFSC PORTB,RB2,0  ;SENSOR B
    GOTO MAIN
    BTFSC PORTE,RE0,0  ;TEMP B1
    GOTO BOMBAB2
    BTFSC PORTE,RE1,0  ;TEMP B2
    GOTO BOMBAB1
    MOVLW B'10011001'
    MOVWF PORTD,0
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    MOVLW B'11110111'
    MOVWF PORTA,0
    GOTO MAIN
    
unaBOMBA    
    BTFSS PORTE,RE0,0
    GOTO BOMBAB1        ;TEMP B1
    GOTO BOMBAB2	

BOMBAB1
    MOVLW B'00001100'
    MOVWF PORTD,0
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    BTFSC PORTB,RB1,0  ;SENSOR A
    GOTO MAIN
    BTFSC PORTE,RE0,0  ;TEMP B1
    GOTO BOMBAB2
    MOVLW B'00000110'
    MOVWF PORTD,0
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    BTFSC PORTB,RB1,0  ;SENSOR A
    GOTO MAIN
    BTFSC PORTE,RE0,0  ;TEMP B1
    GOTO BOMBAB2
    MOVLW B'00000011'
    MOVWF PORTD,0
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    BTFSC PORTB,RB1,0  ;SENSOR A
    GOTO MAIN
    BTFSC PORTE,RE0,0  ;TEMP B1
    GOTO BOMBAB2
    MOVLW B'00001001'
    MOVWF PORTD,0
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    MOVLW B'00110000'
    MOVWF PORTA,0
    GOTO MAIN
    
BOMBAB2
    MOVLW B'11000000'
    MOVWF PORTD,0
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    BTFSC PORTB,RB1,0  ;SENSOR A
    GOTO MAIN
    BTFSC PORTE,RE1,0  ;TEMP B2
    GOTO BOMBAB1
    MOVLW B'01100000'
    MOVWF PORTD,0
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    BTFSC PORTB,RB1,0  ;SENSOR A
    GOTO MAIN
    BTFSC PORTE,RE1,0  ;TEMP B2
    GOTO BOMBAB1
    MOVLW B'00110000'
    MOVWF PORTD,0
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    BTFSC PORTB,RB1,0  ;SENSOR A
    GOTO MAIN
    BTFSC PORTE,RE1,0  ;TEMP B2
    GOTO BOMBAB1
    MOVLW B'10010000'
    MOVWF PORTD,0
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    MOVLW B'01011011'
    MOVWF PORTA,0
    GOTO MAIN
    
DELAY ;ESTRUCTURAMOS EL RETARDO
    CLRF TMR0L
    MOVLW .254
    MOVWF TMR0L
    CLRF WREG
    
ASK
    CPFSEQ TMR0L
    BRA ASK
    RETURN
END





