;ESTE PROGRAMA MUESTRA LA PALABRA HOLA EN UN DISPLAY DE
;7 SEG. TIENE HABILITADA UNA INTERRUPCIÓN EXTERNA (INT0)
;CONECTADA A UN BOTÓN CON RESISTOR PULL DOWN. SI ÉSTA SE
;ACTIVA DEBE ENCENDER UN LED (RC0)  POR UN LAPSO DE 1 SEG.
    
    LIST P=18F4550
    #INCLUDE<P18F4550.INC>
    
    CBLOCK .20
    WREGC
    BSRC
    STATUSC
    TMR0LC
    ENDC
    
    ORG	    .0
    GOTO    SETTINGS
    
    ORG	    .8

BACKUP
    MOVFF   WREG,WREGC
    MOVFF   BSR,BSRC
    MOVFF   STATUS,STATUSC
    MOVFF   TMR0L,TMR0LC
    
EXT_0
    BTFSS   INTCON,INT0IF   ;BANDERA DE LA INT0 ¿TU ME LLAMASTE?
    GOTO    FIN_INT
    BCF	    INTCON,INT0IF   ;BANDERA YA TE LEÍ, REGRESA A 0
    BSF	    PORTC,0,0	    ;ENCIENDE LED
    CALL    DELAY
    CALL    DELAY
    BCF	    PORTC,0,0	    ;APAGA LED
    
FIN_INT
    MOVFF   WREGC,WREG
    MOVFF   BSRC,BSR
    MOVFF   STATUSC,STATUS
    MOVFF   TMR0LC,TMR0L
    RETFIE
    
    
    
SETTINGS
    CLRF    TRISD,0
    CLRF    PORTD,0
    CLRF    TRISC,0
    CLRF    PORTC,0
    SETF    TRISB,0
    CLRF    PORTB,0
    MOVLW   .15
    MOVWF   ADCON1,0
    MOVLW   B'11010111'
    MOVWF   T0CON,0
    MOVLW   B'10010000'  ;HABILITAR DE FORMA GENERAL LAS INTERRUPCIONES
			 ;Y DE MANERA PARTICULAR A LA INT0(B4)
    MOVWF   INTCON,0
    MOVLW   B'11110101'	   ;FLANCO DE SUBIDA PARA INT0
    MOVWF   INTCON2,0
    
MAIN
    MOVLW B'00110111' ;H
    MOVWF PORTD
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    MOVLW B'01111110' ;O
    MOVWF PORTD
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    MOVLW B'00001110' ;L
    MOVWF PORTD
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    MOVLW B'01110111' ;A
    MOVWF PORTD
    CALL DELAY
    CALL DELAY
    CALL DELAY
    CALL DELAY
    BRA MAIN
DELAY
    CLRF    TMR0L,0
    MOVLW   .95
ASK
    CPFSEQ  TMR0L,0
    BRA	    ASK
    RETURN
    END
    
    
    
    
    
    
    
    
    
    
    
			 
			 
			 
			 
			 
			 
			 
			 
    
    
    
    
	


