  
    LIST P=18F4550
    #INCLUDE<P18F4550.INC>
    
;CONFIG1L dir 300000h 	20
		;CONFIG	PLLDIV=1	 ; 
		;CONFIG	CPUDIV=OSC1_PLL2 ;CUANDO SE USA XTAL	
		;CONFIG	USBDIV=2

		;CONFIG1H dir 300001h	08
		CONFIG	FOSC=INTOSCIO_EC ;OSCILADOR INTERNO, RA6 COMO PIN, USB USA OSC EC
		CONFIG	FCMEN=OFF        ;DESHABILITDO EL MONITOREO DEL RELOJ
		CONFIG	IESO=OFF

		;CONFIG2L DIR 300002H	38
		CONFIG	PWRT=ON          ;PWRT HABILITADO
		CONFIG  BOR=OFF		 ;BROWN OUT RESET DESHABILITADO
		CONFIG BORV=3		 ;RESET AL MINIMO VOLTAJE NO UTILZADO EN ESTE CASO
		CONFIG	VREGEN=ON	 ;REULADOR DE USB ENCENDIDO

		;CONFIG2H DIR 300003H	1E
		CONFIG	WDT=OFF          ;WACH DOG DESHABILITADO
		CONFIG WDTPS=32768      ;TIMER DEL WATCHDOG 
		
		;CONFIG3H DIR 300005H	81
		CONFIG	CCP2MX=ON	 ;CCP2 MULTIPLEXADAS CON RC1	
		CONFIG	PBADEN=OFF       ;PUERTO B PINES DEL 0 AL 4 ENTRADAS DIGITALES
		CONFIG  LPT1OSC=OFF	 ;TIMER1 CONFIURADO PARA OPERAR EN BAJA POTENCIA
		CONFIG	MCLRE=ON         ;MASTER CLEAR HABILITADO
		
		;CONFIG4L DIR 300006H	81
		CONFIG	STVREN=ON	 ;SI EL STACK SE LLENA CAUSE RESET		
		CONFIG	LVP=OFF		 ;PROGRAMACIÒN EN BAJO VOLTAJE APAGADO
		CONFIG	ICPRT=OFF	 ;REGISTRO ICPORT DESHABILITADO
		CONFIG	XINST=OFF	 ;SET DE EXTENCION DE INSTRUCCIONES Y DIRECCIONAMIENTO INDEXADO DESHABILITADO

		;CONFIG5L DIR 300008H	0F
		CONFIG	CP0=OFF		 ;LOS BLOQUES DEL CÒDIGO DE PROGRAMA
		CONFIG	CP1=OFF          ;NO ESTAN PROTEGIDOS
		CONFIG	CP2=OFF		 
		CONFIG	CP3=OFF
		
		;CONFIG5H DR 300009H	C0
		CONFIG	CPB=OFF		 ;SECTOR BOOT NO ESTA PROTEGIDO
		CONFIG	CPD=OFF		 ;EEPROM N PROTEGIDA

		;CONFIG6L DIR 30000AH	0F
		CONFIG	 WRT0=OFF	 ;BLOQUES NO PROTEGIDOS CONTRA ESCRITURA
		CONFIG	 WRT1=OFF
		CONFIG	 WRT2=OFF
		CONFIG	 WRT3=OFF

		;CONFIG6H DIR 30000BH	E0
		CONFIG	 WRTC=OFF	 ;CONFIGURACION DE REGISTROS NO PROTEGIDO
		CONFIG	 WRTB=OFF	 ;BLOQUE BOOTEBLE NO PROTEGIDO
		CONFIG	 WRTD=OFF	 ;EEPROMDE DATOS NO PROTGIDA

		;CONFIG7L DIR 30000CH	0F
		CONFIG	 EBTR0=OFF	 ;TABLAS DE LETURA NO PROTEGIDAS
		CONFIG	 EBTR1=OFF
		CONFIG	 EBTR2=OFF
		CONFIG	 EBTR3=OFF

		;CONFIG7H DIR 30000DH	40
		CONFIG	 EBTRB=OFF	 ;TABLAS NO PROTEGIDAS
    
#DEFINE	a	B'1000000'
#DEFINE	b	B'0100000'
#DEFINE	c	B'0010000'
#DEFINE	d	B'0001000'
#DEFINE	e	B'0000100'
#DEFINE	f	B'0000010'
#DEFINE	g	B'0000001'
		
cblock .10
	DATOA
	DATOB
ENDC

ORG	.0	
  GOTO CONFIGURACION
TABLA
    ADDWF   PCL,1,0
    DT a,a,b,g,e,d,c,g,f

TABLA2
    ADDWF   PCL,1,0 
    DT a,a,g,d
    
TABLA3
    ADDWF   PCL,1,0 
    DT f,f,b,e,c    
    
CONFIGURACION
    CLRF  PORTD,0   
    CLRF  TRISD,0   
    SETF  PORTB,0
    MOVLW B'11010111'
    MOVWF T0CON,0
    MOVLW B'00000000'
    MOVWF DATOA,1
    MOVWF DATOB,1
    
 INICIO1
    MOVLW .17
    CPFSLT DATOA,1
    CLRF DATOA,1
    MOVLW .2
    ADDWF DATOA,W,1
    MOVFF WREG,DATOA
    CALL TABLA
    MOVWF PORTD,0
    BTFSC PORTB,RB0,0
    GOTO START2
    CALL delay
    GOTO INICIO1
    
START2
    CLRF DATOB
    CLRF DATOA
    CALL RETARDO
    BTFSS PORTB,RB0,0
    GOTO INICIO2
    GOTO START2

START1
    CLRF DATOA
    CLRF DATOB
    CALL RETARDO
    BTFSS PORTB,RB0,0
    GOTO INICIO1
    GOTO START1
    
INICIO2
    MOVLW .6
    CPFSLT DATOB,1
    CLRF DATOB,1
    MOVLW .2
    ADDWF DATOB,W,0
    MOVFF WREG,DATOB
    CALL TABLA2
    MOVWF PORTD,0
    BTFSC PORTB,RB0,0
    GOTO START3
    CALL delay
    GOTO INICIO2
    
START3
    CLRF DATOB
    CLRF DATOA
    CALL RETARDO
    BTFSS PORTB,RB0,0
    GOTO INICIO3
    GOTO START3
    
INICIO3
    MOVLW .7
    CPFSLT DATOB,1
    CLRF DATOB,1
    MOVLW .2
    ADDWF DATOB,W,0
    MOVFF WREG,DATOB
    CALL TABLA3
    MOVWF PORTD,0
    BTFSC PORTB,RB0,0
    GOTO START1
    CALL delay
    GOTO INICIO3    
    
delay
    CLRF TMR0L,0
    MOVLW .250
ASK
    CPFSEQ  TMR0L,0
    GOTO    ASK
    RETURN
   
RETARDO
    CLRF    TMR0L,0 ;CUENTA DE 0 A 255, PORQUE ES A 8 BITS
    MOVLW   .15
    
ASK2
    CPFSEQ  TMR0L,0 ;PREGUNTA SI W=15, VALE LO MISMO QUE TMR0L
    BRA	    ASK2
    RETURN

END


